Use policy/v1 for pod disruption budget (#4751)
Policy hasn't been a beta API since 4.7
This was causing errors when deploying to integration like:

```
error: unable to recognize "STDIN": no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"
```

Co-authored-by: Nick Carboni <ncarboni@redhat.com>