NI-ISSUE: Fix skipper configuration (#6560)
Currently skipper (+ podman at least) fails with the following error:

```
Error: /home/agentil/.docker: duplicate mount destination
```

because skipper already mounts it by default.