NO-ISSUE Fix call to_url helper function
"to_url" function accepts 3 parameters - host, port and TLS state. This
PR fixes a bug where "to_url" is called with omitting the port,
effectively passing TLS state as the port.

The bug was hit when deploying to a local development environment with
`skipper make deploy-all TARGET=oc-ingres` and causes the following
error to appear

```
make[1]: Entering directory `/home/kmateusz/git/github.com/assisted-service'
python3 ./tools/wait_for_assisted_service.py --target oc-ingress --namespace "assisted-installer" \
	--domain "" --apply-manifest True
Wait for https://assisted-installer.apps-crc.testing:True/ready
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/requests/models.py", line 379, in prepare_url
    scheme, auth, host, port, path, query, fragment = parse_url(url)
  File "/usr/lib/python3.6/site-packages/urllib3/util/url.py", line 401, in parse_url
    return six.raise_from(LocationParseError(source_url), None)
  File "<string>", line 3, in raise_from
urllib3.exceptions.LocationParseError: Failed to parse: https://assisted-installer.apps-crc.testing:True/ready
```

In example above the TLS state is used in a place where HTTP(s) port
should appear because the port is not present in the function call.