NO-ISSUE Fix apiVersion for AgentServiceConfig (#1692)
This PR fixes the incorrect API version for AgentServiceConfig resource
mentioned in the Operator deployment documentation.

The currently used `operators.coreos.com/v1alpha1` does not define
`AgentServiceConfig` causing the following error to be thrown

```
error: unable to recognize "STDIN": no matches for kind "AgentServiceConfig" in version "operators.coreos.com/v1alpha1"
```

Instead, `agent-install.openshift.io/v1beta1` should be used.