NO-ISSUE: fix docker-ce-cli package missing (#5499)
For some reason it's no longer findable even though it seems like we
correctly added the repository:
```
Complete!
Adding repo from:
https://download.docker.com/linux/centos/docker-ce.repo
CentOS Stream 9 - CRB                            12 MB/s | 5.7 MB
00:00
Last metadata expiration check: 0:00:02 ago on Mon Sep 18 13:28:09 2023.
No match for argument: docker-ce-cli
Error: Unable to find a match: docker-ce-cli

```

(see
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/openshift_assisted-service/5497/pull-ci-openshift-assisted-service-master-edge-images/1703760418561855488)

As we're no longer relying much about docker support (as podman takes
preference) we are removing its installation in the
assisted-service-build image.