MGMT-11521: Fix twine upload of assisted-service-client (#4243)
Somewhere at July 31 2022, the 'publish-python-client' job started
failing (see
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/branch-ci-openshift-assisted-service-master-edge-publish-python-client/1553847262923198464)
with the following error:
```
python3 -m twine upload --skip-existing
"/home/assisted-service/build/ci-op-9xpc88fc/assisted-service-client/dist/*.whl"
Traceback (most recent call last):
  File "/usr/lib64/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib64/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/opt/venv/lib64/python3.9/site-packages/twine/__main__.py", line
22, in <module>
    from twine import cli
  File "/opt/venv/lib64/python3.9/site-packages/twine/cli.py", line 18,
in <module>
    from packaging import requirements
ModuleNotFoundError: No module named 'packaging'
```

Apparently there's some need to install the 'packaging' package now.
This change adds 'packaging' dependency (the problem has been resolved
in twine v4.0, but we cannot upgrade because some parts are still built
with py3.6 that is incompatible with twine v4.0).