NO-ISSUE: set PlatformType on ImportCluster
Set explicitly the PlatformType on V2ImportClusterInternal as
the property has been changed to a pointer as part of go-swagger upgrade[1].

I.e. currently, upon day2 cluster creation, assisted-service python
client fails with ValueError on PlatformType model deserialize[2]
as type in the response is null[3].

[1]
https://github.com/openshift/assisted-service/pull/2872/files#diff-3657f5d7ebd63c86fef223229378261d08b79e7d363b6f297cd6595e74683697R27

[2]
:type: PlatformType
"""
if self._configuration.client_side_validation and type is None:
    raise ValueError("Invalid value for `type`, must not be `None`")  # noqa: E501
    ValueError: Invalid value for `type`, must not be `None`

[3]
day2 cluster repsonse:
...
"platform": {
       "ovirt": {},
       "type": null,
       "vsphere": {}
   },