Use policy/v1 for pod disruption budget (#4746)
Policy hasn't been a beta API since 4.7
This was causing errors when deploying to integration like:

```
error: unable to recognize "STDIN": no matches for kind "PodDisruptionBudget" in version "policy/v1beta1"
```